### ISSUE TITLE
add .gitignore

### ISSUE THREAD

**Issue by mitubaEX** [tissya/Blockchain_simulator#2]

**Comment by tissya** [comment]
追加しました

**Comment by mitubaEX** [comment]
[gitignore.io](https://www.gitignore.io/)
上記のサイトでJavaと入力して，それをそのまま貼っつけたら楽ですよ

**Comment by tissya** [comment]
俺の追加したファイルの書き方間違ってる感じ？

**Comment by mitubaEX** [comment]
いや，Javaとかだったら配布する時，jarとかにすると思うけどそれもいらないから，とりあえず脳死で全部入れとけばいいという提案です

**Comment by tissya** [comment]
なるほど
