### ISSUE TITLE
fix ArrayList syntax

### ISSUE THREAD

**Issue by mitubaEX** [tissya/Blockchain_simulator#3]
https://github.com/tissya/Blockchain_simulator/blob/a9d4a0cc925b9bfab4000c0e93c6924ab4f809e5/Node.java#L4

↑のコードを↓のコードに修正してください．
```
public ArrayList<Block> chain = new ArrayList<>(); //ブロックのチェーン
```

**Comment by tissya** [comment]
修正完了しました
