### ISSUE TITLE
🐪と🐍が混じってます

### ISSUE THREAD

**Issue by seihello** [tissya/Blockchain_simulator#4]
Oh, in your code, CamelCase and snake_case are mixed! 

https://github.com/tissya/Blockchain_simulator/blob/8dd55acd02171de1192425632e52c690282b49c8/Main.java#L8-L9
https://github.com/tissya/Blockchain_simulator/blob/8dd55acd02171de1192425632e52c690282b49c8/Blockchain.java#L38

Please modify them shortly!! (Aku Shiro Yo!)

**Comment by tissya** [comment]
たぶんMasterブランチを見ているから混じっているのかと
Kill_Errorブランチでは修正済みです

**Comment by seihello** [comment]
Oh, I'm so sorry. My bad.
